### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by ilias1111** [phiresky/fbstats#2] opened 2014-06-06 12:25 UTC
First of all I would like to say that your app had helped me too much, but the last month I can;t use it. I enter the site i put my id i do all the thinks as you say but i'm not able to see the statistics, its keep been in a loop for ever saying Checking permissions , plss i want help, your app is mandatory i would even pay for that app.

Thank your for your precious time

**Comment by phiresky** [comment] 2014-06-10 21:25
Hi,
sorry, but without more information I can't really help.
Can you use Chrome or Firefox, open the dev. console (F12 or right click->inspect element), reload the page and tell me the log from the console? thanks

**Comment by ilias1111** [comment] 2014-06-10 21:29
Thank you for your answer,

Unfortunately I m not able to enter from PC but only from tablet right now so I m not able to do right now what you said, so is anything other I can do to provide you more info?

**Comment by phiresky** [comment] 2014-06-10 21:41
Well, I just added a debug mode: http://phiresky.github.io/fbstats/?debug 
This should theoretically view error messages on the top of the page, but it doesn't seem to work for internal errors from the facebook api

**Comment by ilias1111** [comment] 2014-06-10 21:45
Well for sure it's not your application error but a Facebook one  so I will try what you said and I will sent you the log, thank you for your time I will sent you asap

**Comment by ilias1111** [comment] 2014-06-11 12:38
The log:
The "fb-root" div has not been created, auto-creating all.js:53
Uncaught ReferenceError: txt is not defined all.js:82

**Comment by phiresky** [comment] 2014-06-11 13:55
The fb-root div message is normal,
the txt is not defined should not happen, but no idea where it comes from.
do you get a stack trace? ( arrow symbol left of the message which expands
to more lines)

I'm using an older version of the facebook api, I'll see if I can upgrade

2014-06-11 14:38 GMT+02:00 ilias1111 notifications@github.com:

**Comment by phiresky** [comment] 2014-06-11 14:13
I can reproduce this when creating a new app and using that ID. Same error. The new API seems to be the problem.

from facebook.com:

> For apps created on or after April 30th 2014, making API calls without specifying a version number is equivalent to calling v2.0 of the API. These apps won't be able to call v1.0 of the API.

did you create your app after that date?

**Comment by ilias1111** [comment] 2014-06-11 14:19
Yes its after that date :(

**Comment by ilias1111** [comment] 2014-06-11 14:27
It fixed (I used an old app i had) it works now :dancer: thank you so much think about a standalone app for web or android I would pay for more features :)

**Comment by phiresky** [comment] 2014-06-11 14:46
So I just looked at the new API from facebook - seems like this will be a wontfix for anything created since may, with the new version they only allow 20 requests at a time which is far to little to get anywhere..

**Comment by ilias1111** [comment] 2014-06-11 14:51
:( speaking like a statistics junkie  ( as well as Facebook  messanger  junkie} I literally love your app,  the 20 requests are from your side or for us? It means that after 20 requests we can't continue?

**Comment by phiresky** [comment] 2014-06-11 14:54
Every request to facebook can only contain 20 timestamps (currently 500). After 50 calls or so I get blocked for an unspecified amount of time. I already had a version using this method as it does not require creating your own app, but it's far too slow..

**Comment by ilias1111** [comment] 2014-06-11 14:59
Each timestamp  is a single message?

**Comment by phiresky** [comment] 2014-06-11 15:01
Yes. Currently only the date for each message is downloaded, 500 at a time, not the message contents.

**Comment by ilias1111** [comment] 2014-06-11 15:04
so after 25.000 messages there is a problem?? If yes Facebook is dump if they were smart the would implement a native system like that even with more statistics.

**Comment by phiresky** [comment] 2014-06-11 15:08
With the new API after about 2000 messages. With the old one it seems to be inconsistent.
So I think I got it to work again for apps from after v2.0, but the calls are using deprecated endpoints which will probably be removed soon.

**Comment by ilias1111** [comment] 2014-06-11 15:17
WTF facebook s***s I use facebook and not viber or hangouts only because of your app they are just kiling themselfes now.Also is a way to export the stamps in a way is easy to do analysis in ecxel?

**Comment by phiresky** [comment] 2014-06-11 15:20
Yes, there is a "export timestamps to CSV" button below the graphs" ;)

I'm also right now trying to add the ability to get the message contents
and send direction (recieved or sent) too.

2014-06-11 17:17 GMT+02:00 ilias1111 notifications@github.com:

**Comment by phiresky** [comment] 2014-06-12 19:52
I just rewrote large parts in typescript on the dev branch. In/Out messages are now separate and it is possible to download the messages themselves: http://phiresky.github.io/fbstats/dev/

**Closed as completed by phiresky** 2014-06-12 19:52 UTC
